M48
; DRILL file {KiCad (6.0.4-0)} date Monday, May 16, 2022 at 08:16:00 AM
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2022-05-16T08:16:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X25879Y-12147
X31784Y-12147
X38416Y-12147
X44321Y-12147
T0
M30
