M48
; DRILL file {KiCad (6.0.4-0)} date Sunday, August 07, 2022 at 01:11:57 PM
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2022-08-07T13:11:57-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X26072Y-12147
X31978Y-12147
X38046Y-12147
X43951Y-12147
T0
M30
